# Generated by Django 5.0.1 on 2024-06-10 11:13

import app1.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_userenrolled_facial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEnrolled50',
            fields=[
                ('sr', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(choices=[('role1', 'Role 1'), ('role2', 'Role 2')], max_length=100)),
                ('mycompany_id', models.CharField(max_length=10)),
                ('tag_id', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=100)),
                ('orientation', models.FileField(blank=True, null=True, upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg'])])),
                ('facial_data', models.ImageField(blank=True, null=True, upload_to=app1.models.user_image_upload_path, verbose_name='Facial Data')),
                ('my_comply', models.ImageField(blank=True, null=True, upload_to='compliance_images/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
