# Generated by Django 5.0.1 on 2024-06-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_userenrolled50'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEnrolled50',
        ),
    ]
