# Generated by Django 5.0.1 on 2024-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_delete_userenrolled50'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenrolled',
            name='job_role',
        ),
        migrations.AddField(
            model_name='site',
            name='location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='site_pictures/'),
        ),
        migrations.AddField(
            model_name='userenrolled',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures/'),
        ),
    ]
