# Generated by Django 5.0.1 on 2024-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='asset_pictures/'),
        ),
    ]
