# Generated by Django 5.0.1 on 2024-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_asset_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrolled',
            name='job_role',
            field=models.CharField(choices=[('role1', 'Role 1'), ('role2', 'Role 2')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
