# Generated by Django 5.0.1 on 2024-06-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_userenrolled_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
