# Generated by Django 5.0.1 on 2024-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_userenrolled_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
