# Generated by Django 5.0.1 on 2024-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_userenrolled_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
