# Generated by Django 5.0.1 on 2024-07-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_customuser_first_name_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tag_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
