# Generated by Django 5.0.1 on 2024-07-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=50),
        ),
    ]
