# Generated by Django 5.0.1 on 2024-09-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
