# Generated by Django 5.0.1 on 2024-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='tag_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
