# Generated by Django 5.0.1 on 2024-09-04 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_alter_userenrolled_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientation',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.site'),
            preserve_default=False,
        ),
    ]
