# Generated by Django 5.0.1 on 2024-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_orientation_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrolled',
            name='identity_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
