# Generated by Django 5.0.1 on 2024-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_userenrolled_identity_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrolled',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userenrolled',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userenrolled',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userenrolled',
            name='userIdentifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
