# Generated by Django 5.0.1 on 2024-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_userenrolled_family_name_userenrolled_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='first_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
