# Generated by Django 5.0.1 on 2024-09-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_alter_userenrolled_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
