# Generated by Django 5.0.1 on 2024-09-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
