# Generated by Django 5.0.1 on 2024-09-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
